FROM node:22-alpine AS build
WORKDIR /app
ARG VITE_API_URL=/api
ARG VITE_OIDC_ISSUER
ARG VITE_OIDC_CLIENT_ID
ARG VITE_OIDC_SCOPE="openid profile email"
ARG VITE_OIDC_REDIRECT_URI
ARG VITE_ALLOW_TOKEN_INJECTION=false
ENV VITE_API_URL=$VITE_API_URL \
    VITE_OIDC_ISSUER=$VITE_OIDC_ISSUER \
    VITE_OIDC_CLIENT_ID=$VITE_OIDC_CLIENT_ID \
    VITE_OIDC_SCOPE=$VITE_OIDC_SCOPE \
    VITE_OIDC_REDIRECT_URI=$VITE_OIDC_REDIRECT_URI \
    VITE_ALLOW_TOKEN_INJECTION=$VITE_ALLOW_TOKEN_INJECTION
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
ENV API_PROXY_TARGET=http://host.docker.internal:8000
ENV NGINX_ENVSUBST_FILTER=API_PROXY_TARGET
COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
