import { FormEvent, useEffect, useState } from 'react'
import { Building2, FolderPlus, UserPlus } from 'lucide-react'
import { api } from '../lib/api'
import { Empty, ErrorBox, Loading, PageHeader, Status } from '../components/ui'
import type { Organization, Principal, Project, Role } from '../types'

export function AdministrationPage({ token, onProjectsChanged }: { token: string; onProjectsChanged: () => Promise<void> }) {
  const [organizations, setOrganizations] = useState<Organization[]>([]), [organizationId, setOrganizationId] = useState('')
  const [projects, setProjects] = useState<Project[]>([]), [principals, setPrincipals] = useState<Principal[]>([]), [roles, setRoles] = useState<Role[]>([])
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [projectName, setProjectName] = useState(''), [namespace, setNamespace] = useState('')
  const [issuer, setIssuer] = useState(''), [subject, setSubject] = useState(''), [username, setUsername] = useState(''), [roleId, setRoleId] = useState('')
  useEffect(() => { api.organizations(token).then(items => { setOrganizations(items); setOrganizationId(items[0]?.id || '') }).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [token])
  const load = async () => { if (!organizationId) return; setLoading(true); try { const [p,u,r] = await Promise.all([api.organizationProjects(token,organizationId), api.organizationPrincipals(token,organizationId), api.organizationRoles(token,organizationId)]); setProjects(p); setPrincipals(u); setRoles(r); setRoleId(current => current || r[0]?.id || ''); setError('') } catch(e) { setError(e instanceof Error ? e.message : 'Could not load organization') } finally { setLoading(false) } }
  useEffect(() => { load() }, [organizationId]) // eslint-disable-line react-hooks/exhaustive-deps
  async function createProject(e: FormEvent) { e.preventDefault(); try { await api.createProject(token,organizationId,{ name: projectName, namespace }); setProjectName(''); setNamespace(''); await Promise.all([load(), onProjectsChanged()]) } catch(e) { setError(e instanceof Error ? e.message : 'Could not create project') } }
  async function createPrincipal(e: FormEvent) { e.preventDefault(); try { await api.createPrincipal(token,organizationId,{ issuer, external_subject: subject, username, role_id: roleId }); setSubject(''); setUsername(''); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Could not create principal') } }
  async function toggleProject(project: Project) { try { await api.updateProject(token,project.id,{ enabled: !project.enabled }); await Promise.all([load(), onProjectsChanged()]) } catch(e) { setError(e instanceof Error ? e.message : 'Could not update project') } }
  async function togglePrincipal(principal: Principal) { try { await api.updatePrincipal(token,organizationId,principal.id,{ enabled: !principal.enabled }); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Could not update principal') } }
  return <div className="page"><PageHeader eyebrow="Platform administration" title="Organizations" text="Provision projects and OIDC-backed identities." />{error && <ErrorBox message={error} />}
    <label className="organization-picker">Organization<select value={organizationId} onChange={e=>setOrganizationId(e.target.value)}>{organizations.map(o=><option key={o.id} value={o.id}>{o.display_name}</option>)}</select></label>
    {loading ? <Loading /> : !organizationId ? <Empty icon={<Building2 />} title="No organizations" text="Your identity has no organization memberships." /> : <div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Projects</h2><p>Organization namespaces and availability.</p></div><FolderPlus /></div><div className="member-list">{projects.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.namespace}</small></span><Status value={p.enabled?'Enabled':'Disabled'} /><button className="button secondary compact" onClick={()=>toggleProject(p)}>{p.enabled?'Disable':'Enable'}</button></div>)}</div><form className="stack-form" onSubmit={createProject}><h3>Create project</h3><label>Name<input required value={projectName} onChange={e=>setProjectName(e.target.value)} /></label><label>Namespace<input required pattern="[a-z0-9]([-a-z0-9]*[a-z0-9])?" value={namespace} onChange={e=>setNamespace(e.target.value)} /></label><button className="button primary"><FolderPlus /> Create project</button></form></section>
      <section className="panel"><div className="panel-head"><div><h2>Principals</h2><p>External identities mapped into this organization.</p></div><UserPlus /></div><div className="member-list">{principals.map(p=><div key={p.id}><span><b>{p.display_name || p.username || 'Principal'}</b><small>{p.email || p.id}</small></span><Status value={p.enabled?'Enabled':'Disabled'} /><button className="button secondary compact" onClick={()=>togglePrincipal(p)}>{p.enabled?'Disable':'Enable'}</button></div>)}</div><form className="stack-form" onSubmit={createPrincipal}><h3>Add principal</h3><label>OIDC issuer<input required type="url" value={issuer} onChange={e=>setIssuer(e.target.value)} placeholder="https://identity.example/realms/platform" /></label><label>External subject<input required value={subject} onChange={e=>setSubject(e.target.value)} /></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} /></label><label>Organization role<select required value={roleId} onChange={e=>setRoleId(e.target.value)}>{roles.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><button className="button primary"><UserPlus /> Add principal</button></form></section></div>}
  </div>
}
