import { FormEvent, useEffect, useState } from 'react'
import { Boxes, Plus, Search, ServerCog, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { api } from '../lib/api'
import { Empty, ErrorBox, Loading, PageHeader, Status } from '../components/ui'
import { usePolling } from '../lib/usePolling'
import type { Cluster, ManagementCluster, Project, ProviderReference } from '../types'

export function ClustersPage({ token, projects }: { token: string; projects: Project[] }) {
  const [params, setParams] = useSearchParams(), [clusters, setClusters] = useState<Cluster[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [search, setSearch] = useState('')
  const [project, setProject] = useState(projects[0]?.id || ''), [name, setName] = useState(''), [version, setVersion] = useState('v1.31.1'), [workers, setWorkers] = useState(3), [saving, setSaving] = useState(false)
  const [managementClusters, setManagementClusters] = useState<ManagementCluster[]>([]), [providers, setProviders] = useState<ProviderReference[]>([]), [managementCluster, setManagementCluster] = useState(''), [provider, setProvider] = useState('')
  const showCreate = params.get('create') === 'true'
  const load = async () => { setLoading(true); try { setClusters((await Promise.all(projects.map(p => api.clusters(token, p.id)))).flat()); setError('') } catch(e) { setError(e instanceof Error ? e.message : 'Could not load clusters') } finally { setLoading(false) } }
  useEffect(() => { load() }, [token, projects]) // eslint-disable-line react-hooks/exhaustive-deps
  usePolling(load, clusters.some(c => c.observed_revision !== c.desired_revision))
  useEffect(() => { if (!showCreate) return; Promise.all([api.managementClusters(token), project ? api.providerReferences(token, project) : Promise.resolve([])]).then(([m,p]) => { setManagementClusters(m); setProviders(p); setManagementCluster(current => current || m[0]?.id || ''); setProvider(p[0]?.id || '') }).catch(e => setError(e instanceof Error ? e.message : 'Could not load cluster options')) }, [showCreate, project, token])
  async function create(e: FormEvent) { e.preventDefault(); setSaving(true); try { await api.createCluster(token, { project_id: project, management_cluster_id: managementCluster, provider_reference_id: provider, name, spec: { kubernetes: { version }, control_plane: { replicas: 3, node_profile: 'control' }, worker_node_types: [{ name: 'workers', role: 'worker', replicas: workers, node_profile: 'compute' }], machine_health_check: { enabled: true }, features: { audit_logs: true, metrics: true } } }); setParams({}); setName(''); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Create failed') } finally { setSaving(false) } }
  const filtered = clusters.filter(c => c.name.toLowerCase().includes(search.toLowerCase()))
  return <div className="page"><PageHeader eyebrow="Infrastructure" title="Clusters" text="Provision and manage your Kubernetes fleet." actions={<button className="button primary" onClick={() => setParams({create:'true'})}><Plus /> New cluster</button>} />{error && <ErrorBox message={error} />}
    <div className="toolbar"><div className="search"><Search /><input placeholder="Search clusters…" value={search} onChange={e => setSearch(e.target.value)} /></div><span>{filtered.length} cluster{filtered.length === 1 ? '' : 's'}</span></div>
    {loading ? <Loading /> : filtered.length ? <div className="card-grid">{filtered.map(c => <Link className="cluster-card" to={`/clusters/${c.id}`} key={c.id}><div><span className="cluster-icon"><ServerCog /></span><Status value={c.observed_revision === c.desired_revision ? 'Healthy' : 'Syncing'} /></div><h3>{c.name}</h3><p>{projects.find(p => p.id === c.project_id)?.name || 'Unknown project'}</p><dl><div><dt>Desired</dt><dd>rev {c.desired_revision}</dd></div><div><dt>Applied</dt><dd>{c.applied_revision ? `rev ${c.applied_revision}` : '—'}</dd></div><div><dt>Observed</dt><dd>{c.observed_revision ? `rev ${c.observed_revision}` : '—'}</dd></div></dl></Link>)}</div> : <Empty icon={<Boxes />} title="No clusters found" text={search ? 'Try another search.' : 'Provision your first cluster in a few steps.'} action={!search && <button className="button primary" onClick={() => setParams({create:'true'})}><Plus /> Create cluster</button>} />}
    {showCreate && <div className="modal-wrap"><button className="backdrop" onClick={() => setParams({})} aria-label="Close"/><div className="modal"><div className="modal-head"><div><span className="eyebrow">New workload</span><h2>Create cluster</h2><p>Start with secure, production-minded defaults.</p></div><button className="icon-button" onClick={() => setParams({})} aria-label="Close create cluster"><X /></button></div><form onSubmit={create}><label>Cluster name<input required pattern="[a-z0-9-]+" placeholder="payments-prod" value={name} onChange={e => setName(e.target.value)} /><small>Lowercase letters, numbers, and hyphens.</small></label><label>Project<select value={project} onChange={e => setProject(e.target.value)}>{projects.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="form-row"><label>Management cluster<select required value={managementCluster} onChange={e=>setManagementCluster(e.target.value)}><option value="">Select a target</option>{managementClusters.map(m=><option value={m.id} key={m.id}>{m.name} · {m.region}</option>)}</select></label><label>Provider reference<select required value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Select credentials</option>{providers.map(p=><option value={p.id} key={p.id}>{p.name} · {p.provider}</option>)}</select></label></div>{!providers.length && <div className="callout">This project has no provider references. Add one under Projects &amp; access first.</div>}<div className="form-row"><label>Kubernetes version<input value={version} onChange={e => setVersion(e.target.value)} pattern="v?1\.\d+\.\d+" required /></label><label>Worker nodes<input type="number" min="0" max="1000" value={workers} onChange={e => setWorkers(Number(e.target.value))} /></label></div><div className="callout">A 3-node control plane, machine health checks, metrics, and audit logs are enabled.</div><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setParams({})}>Cancel</button><button className="button primary" disabled={saving || !managementCluster || !provider}>{saving ? 'Creating…' : 'Create cluster'}</button></div></form></div></div>}
  </div>
}
