import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, Boxes, RefreshCw, Scaling, Sparkles } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../lib/api'
import { ErrorBox, JsonView, Loading, PageHeader, Status } from '../components/ui'
import type { Cluster, Json, Operation } from '../types'

type Tab = 'overview' | 'operations' | 'revisions' | 'resources' | 'conditions'
export function ClusterDetail({ token }: { token: string }) {
  const { id = '' } = useParams(), [cluster, setCluster] = useState<Cluster>(), [operations, setOperations] = useState<Operation[]>([]), [health, setHealth] = useState<Json>(), [data, setData] = useState<Json[]>([]), [tab, setTab] = useState<Tab>('overview'), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [pool, setPool] = useState('workers'), [replicas, setReplicas] = useState(3), [version, setVersion] = useState('v1.32.0'), [busy, setBusy] = useState(false)
  const load = async () => { try { const [c, o, h] = await Promise.all([api.cluster(token,id), api.operations(token,id), api.health(token,id)]); setCluster(c); setOperations(o); setHealth(h); setError('') } catch(e) { setError(e instanceof Error ? e.message : 'Unable to load cluster') } finally { setLoading(false) } }
  useEffect(() => { load() }, [id, token]) // eslint-disable-line react-hooks/exhaustive-deps
  async function choose(next: Tab) { setTab(next); if (next === 'revisions') setData(await api.revisions(token,id)); if (next === 'resources') setData(await api.resources(token,id)); if (next === 'conditions') setData(await api.conditions(token,id)) }
  async function mutate(e: FormEvent, kind: 'scale'|'upgrade') { e.preventDefault(); setBusy(true); try { if (kind === 'scale') await api.scale(token,id,pool,replicas); else await api.upgrade(token,id,version); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Operation failed') } finally { setBusy(false) } }
  if (loading) return <div className="page"><Loading /></div>
  return <div className="page"><Link to="/clusters" className="back-link"><ArrowLeft /> Back to clusters</Link>{error && <ErrorBox message={error} />}{cluster && <><PageHeader eyebrow="Workload cluster" title={cluster.name} text={`ID ${cluster.id}`} actions={<><Status value={cluster.observed_revision === cluster.desired_revision ? 'Healthy' : 'Syncing'} /><button className="button secondary" onClick={load}><RefreshCw /> Refresh</button></>} />
    <div className="tabs">{(['overview','operations','revisions','resources','conditions'] as Tab[]).map(t => <button className={tab===t?'active':''} onClick={() => choose(t)} key={t}>{t}</button>)}</div>
    {tab === 'overview' && <div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Reconciliation</h2><p>Control-plane revision state</p></div></div><div className="revision-flow"><span><b>{cluster.desired_revision}</b><small>Desired</small></span><i /><span><b>{cluster.applied_revision || '—'}</b><small>Applied</small></span><i /><span><b>{cluster.observed_revision || '—'}</b><small>Observed</small></span></div><h3>Normalized health</h3><JsonView value={health} /></section><section className="panel action-panel"><div><Scaling /><h2>Scale workers</h2><p>Set the replica count for a worker node type.</p><form onSubmit={e => mutate(e,'scale')}><label>Worker pool<input value={pool} onChange={e=>setPool(e.target.value)} /></label><label>Replicas<input type="number" min="0" max="1000" value={replicas} onChange={e=>setReplicas(Number(e.target.value))} /></label><button className="button primary" disabled={busy}>Scale cluster</button></form></div><div><Sparkles /><h2>Upgrade Kubernetes</h2><p>Create an immutable revision with a newer version.</p><form onSubmit={e => mutate(e,'upgrade')}><label>Target version<input value={version} onChange={e=>setVersion(e.target.value)} pattern="v?1\.\d+\.\d+" /></label><button className="button secondary" disabled={busy}>Start upgrade</button></form></div></section></div>}
    {tab === 'operations' && <section className="panel table-wrap"><table><thead><tr><th>Operation</th><th>State</th><th>Target</th><th>Created</th></tr></thead><tbody>{operations.map(o=><tr key={o.id}><td><b>{o.kind}</b><small>{o.id}</small></td><td><Status value={o.state}/></td><td>rev {o.target_revision}</td><td>{new Date(o.created_at).toLocaleString()}</td></tr>)}</tbody></table></section>}
    {['revisions','resources','conditions'].includes(tab) && <section className="panel"><div className="panel-head"><div><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2><p>Raw API data for inspection and troubleshooting.</p></div><Boxes /></div><JsonView value={data} /></section>}</>}
  </div>
}
