import { FormEvent, useEffect, useState } from 'react'
import { CloudCog, Plus, Trash2 } from 'lucide-react'
import { api } from '../lib/api'
import { Empty, ErrorBox, Loading, PageHeader } from '../components/ui'
import type { Json, NodeProfile, Project, ProviderReference } from '../types'

function parseObject(value: string): Record<string, Json> { const result: unknown = JSON.parse(value); if (!result || Array.isArray(result) || typeof result !== 'object') throw new Error('Configuration must be a JSON object.'); return result as Record<string, Json> }

export function ConfigurationPage({ token, projects }: { token: string; projects: Project[] }) {
  const [projectId, setProjectId] = useState(projects[0]?.id || ''), [providers, setProviders] = useState<ProviderReference[]>([]), [profiles, setProfiles] = useState<NodeProfile[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [provider, setProvider] = useState('vsphere'), [providerName, setProviderName] = useState(''), [secret, setSecret] = useState(''), [configuration, setConfiguration] = useState('{}')
  const [profileName, setProfileName] = useState(''), [providerId, setProviderId] = useState(''), [specification, setSpecification] = useState('{}')
  const load = async () => { if (!projectId) { setLoading(false); return } setLoading(true); try { const [refs,nodes] = await Promise.all([api.providerReferences(token,projectId), api.nodeProfiles(token,projectId)]); setProviders(refs); setProfiles(nodes); setProviderId(current => refs.some(r=>r.id===current) ? current : refs[0]?.id || ''); setError('') } catch(e) { setError(e instanceof Error ? e.message : 'Could not load configuration') } finally { setLoading(false) } }
  useEffect(() => { load() }, [projectId, token]) // eslint-disable-line react-hooks/exhaustive-deps
  async function addProvider(e: FormEvent) { e.preventDefault(); try { await api.createProviderReference(token,projectId,{ provider, name: providerName, secret_reference: secret, configuration: parseObject(configuration) }); setProviderName(''); setSecret(''); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Could not create provider reference') } }
  async function addProfile(e: FormEvent) { e.preventDefault(); try { await api.createNodeProfile(token,projectId,{ provider_reference_id: providerId, name: profileName, specification: parseObject(specification) }); setProfileName(''); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Could not create node profile') } }
  async function remove(kind: 'provider'|'profile', id: string) { if (!window.confirm(`Delete this ${kind}?`)) return; try { if (kind==='provider') await api.deleteProviderReference(token,projectId,id); else await api.deleteNodeProfile(token,projectId,id); await load() } catch(e) { setError(e instanceof Error ? e.message : `Could not delete ${kind}`) } }
  return <div className="page"><PageHeader eyebrow="Infrastructure configuration" title="Providers & node profiles" text="Configure reusable credentials and machine templates for cluster creation." />{error && <ErrorBox message={error} />}<label className="organization-picker">Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{loading ? <Loading /> : !projectId ? <Empty icon={<CloudCog />} title="No projects" text="Create a project before configuring infrastructure." /> : <div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Provider references</h2><p>Safe metadata is shown; secret values are never returned.</p></div></div><div className="member-list">{providers.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.provider}</small></span><button className="icon-button danger" onClick={()=>remove('provider',p.id)} aria-label={`Delete ${p.name}`}><Trash2 /></button></div>)}</div><form className="stack-form" onSubmit={addProvider}><h3>Add provider</h3><label>Provider<input required value={provider} onChange={e=>setProvider(e.target.value)} /></label><label>Name<input required value={providerName} onChange={e=>setProviderName(e.target.value)} /></label><label>Secret reference<input required value={secret} onChange={e=>setSecret(e.target.value)} placeholder="vault://platform/credentials" /></label><label>Configuration (JSON)<textarea rows={4} value={configuration} onChange={e=>setConfiguration(e.target.value)} /></label><button className="button primary"><Plus /> Add provider</button></form></section>
      <section className="panel"><div className="panel-head"><div><h2>Node profiles</h2><p>Provider-specific machine specifications.</p></div></div><div className="member-list">{profiles.map(p=><div key={p.id}><span><b>{p.name}</b><small>{providers.find(r=>r.id===p.provider_reference_id)?.name || p.provider_reference_id}</small></span><button className="icon-button danger" onClick={()=>remove('profile',p.id)} aria-label={`Delete ${p.name}`}><Trash2 /></button></div>)}</div><form className="stack-form" onSubmit={addProfile}><h3>Add node profile</h3><label>Name<input required pattern="[a-z0-9]([-a-z0-9]*[a-z0-9])?" value={profileName} onChange={e=>setProfileName(e.target.value)} /></label><label>Provider reference<select required value={providerId} onChange={e=>setProviderId(e.target.value)}>{providers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Specification (JSON)<textarea rows={6} value={specification} onChange={e=>setSpecification(e.target.value)} /></label><button className="button primary" disabled={!providerId}><Plus /> Add profile</button></form></section></div>}</div>
}
